---
version: '3'

services:
  haproxy:
    image: danie1k/homelab-haproxy:rolling
    command:
      - "python /usr/local/bin/docker-network-monitor.py"
      - "haproxy -W -db -p /var/run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg"
    environment:
      HAPROXY_CONFIG_FILE: /usr/local/etc/haproxy/haproxy.cfg
      HAPROXY_PID_FILE: /var/run/haproxy.pid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
