---
version: '3'

services:
  haproxy:
    image: danie1k/homelab-haproxy:rolling
    command:
      - "python /docker_network_monitor/monitor.py"
      - "haproxy -W -db -p /var/run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg"
    networks:
      - bridge  # This network is added by Docker by default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  hello-world:
    image: nginxdemos/hello
    labels:
      haproxy.source_port: "80"
      haproxy.target_port: "80"
    networks:
      - bridge  # This network is added by Docker by default
